name: carbon-generics
on:
  push:
    paths:
      - carbon-generics/**
      - .github/workflows/carbon-generics.yml
    branches:
      - main
  pull_request:
    paths:
      - carbon-generics/**
      - .github/workflows/carbon-generics.yml
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: carbon-generics
    strategy:
      matrix:
        node-version:
          - 14.x
          - 16.x
          - 17.x
    steps:
      - uses: actions/checkout@v2
      - run: corepack enable pnpm
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          cache-dependency-path: carbon-generics/pnpm-lock.yaml
      - run: pnpm i
      # - run: pnpm lint
      - run: pnpm tsc --noEmit
      - run: pnpm build
