name: carbon-felte
on:
  push:
    paths:
      - carbon-felte/**
      - .github/workflows/carbon-felte.yml
    branches:
      - main
  pull_request:
    paths:
      - carbon-felte/**
      - .github/workflows/carbon-felte.yml
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: carbon-felte
    strategy:
      matrix:
        node-version:
          - 14.x
          - 16.x
          - 17.x
          - 18.x
    steps:
      - uses: actions/checkout@v3
      - run: corepack enable pnpm
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          # cache: 'pnpm'
          cache-dependency-path: carbon-felte/pnpm-lock.yaml
      - run: pnpm i
      - run: pnpm lint
      - run: pnpm check
      - run: pnpm tsc --noEmit
      - run: pnpm build
