on:
  workflow_dispatch:
    inputs:
      version:
        description: 'version'
        required: true
        default: 'patch' 
        type: choice
        options:
        - patch
        - minor
        - major 
jobs:
  version-up:
    runs-on: unintu-latest
    steps:
      - run: echo ${{ inputs.version }} 
