name: smui6
on:
  push:
    paths:
      - smui6/**
      - .github/workflows/smui6.yml
    branches:
      - main
  pull_request:
    paths:
      - smui6/**
      - .github/workflows/smui6.yml
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: smui6
    strategy:
      matrix:
        node-version:
          - 14.x
          - 16.x
          - 17.x
    steps:
      - uses: actions/checkout@v2
      - run: corepack enable pnpm
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          cache-dependency-path: smui6/pnpm-lock.yaml
      - run: pnpm i
      - run: pnpm lint
      - run: pnpm check
      - run: pnpm tsc --noEmit
      - run: pnpm build
